Repository TelcreaT/AllInOneCommerce, pull requests merged in 2021-04, with the labels that each got.

#6 Important BUG fixes in Backend
  src/main/java/com/telcreat/aio/model/CheckOutEditForm.java
  src/main/java/com/telcreat/aio/model/ShopEditForm.java
  src/main/java/com/telcreat/aio/model/User.java
  src/main/java/com/telcreat/aio/repo/ShopRepo.java
  src/main/java/com/telcreat/aio/repo/VariantRepo.java
  src/main/java/com/telcreat/aio/service/ItemService.java
  src/main/java/com/telcreat/aio/service/ShopService.java
  src/main/java/com/telcreat/aio/service/UserService.java
  src/main/java/com/telcreat/aio/service/VariantService.java
  src/main/java/com/telcreat/aio/viewController/errorController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/checkout.html
  src/main/resources/templates/editShop.html
  src/main/resources/templates/editUser.html
  src/main/resources/templates/error/error-403.html
  src/main/resources/templates/shop.html
  src/main/resources/templates/shopProducts.html
Labels: bug, enhancement

#8 Added necessary attribute for itemService method (get client's IP address)
  src/main/java/com/telcreat/aio/model/Shop.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/editShop.html
  src/main/resources/templates/editUser.html
  src/main/resources/templates/search.html
Labels: enhancement

#9 Minor changes: code enhancement.
  src/main/java/com/telcreat/aio/service/ShopOrderService.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
Labels: enhancement

#11 Major change in viewController
  src/main/java/com/telcreat/aio/viewController/authController.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/userController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
Labels: enhancement

#14 OrderController.java + order.html
  src/main/java/com/telcreat/aio/viewController/orderController.java
  src/main/resources/templates/order.html
Labels: enhancement

#15 Aresti PUll Request - From Aresti to FrontEnd
  src/main/java/com/telcreat/aio/model/Shop.java
  src/main/java/com/telcreat/aio/model/ShopEditForm.java
  src/main/java/com/telcreat/aio/repo/ItemRepo.java
  src/main/java/com/telcreat/aio/service/ItemService.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/userController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/editShop.html
  src/main/resources/templates/editUser.html
  src/main/resources/templates/h_about.html
  src/main/resources/templates/h_cesta.html
  src/main/resources/templates/h_orders.html
  src/main/resources/templates/h_pago.html
  src/main/resources/templates/h_products.html
  src/main/resources/templates/h_services.html
  src/main/resources/templates/index.html
  src/main/resources/templates/item.html
  src/main/resources/templates/shop.html
Labels: bug, enhancement

#17 #2 Addition of the fragments.html file and its implementation in index.html
  src/main/resources/static/css/style.css
  src/main/resources/templates/AIO_template.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
Labels: enhancement

#21 Implementation of fragment functionality for HTML code blocks
  src/main/resources/templates/addProduct.html
  src/main/resources/templates/auth.html
  src/main/resources/templates/changePassword.html
  src/main/resources/templates/editShop.html
  src/main/resources/templates/editUser.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/h_about.html
  src/main/resources/templates/h_cesta.html
  src/main/resources/templates/h_orders.html
  src/main/resources/templates/h_pago.html
  src/main/resources/templates/h_products.html
  src/main/resources/templates/h_services.html
  src/main/resources/templates/item.html
  src/main/resources/templates/manageProducts.html
  src/main/resources/templates/order.html
  src/main/resources/templates/recoverPassword.html
  src/main/resources/templates/shop.html
  src/main/resources/templates/verification.html
Labels: enhancement

#23 Correction of index.html
  src/main/resources/templates/index.html
Labels: bug

#25 Fixed button link in shop.html
  src/main/resources/templates/shop.html
Labels: bug

#27 IMPORTANT CHANGES IN HTML AND CONTROLLERS
  src/main/java/com/telcreat/aio/model/Item.java
  src/main/java/com/telcreat/aio/model/Variant.java
  src/main/java/com/telcreat/aio/repo/VariantRepo.java
  src/main/java/com/telcreat/aio/service/ItemService.java
  src/main/java/com/telcreat/aio/service/VariantService.java
  src/main/java/com/telcreat/aio/viewController/itemController.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/variantController.java
  src/main/resources/templates/item.html
Labels: bug, enhancement

#29 Changes in style.css
  src/main/resources/static/css/style.css
Labels: enhancement

#32 Updates in some HTMLs
  src/main/resources/static/css/style.css
  src/main/resources/templates/auth.html
  src/main/resources/templates/changePassword.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/recoverPassword.html
  src/main/resources/templates/verification.html
Labels: enhancement

#34 Major changes in View Controllers
  src/main/java/com/telcreat/aio/model/ItemEditForm.java
  src/main/java/com/telcreat/aio/viewController/itemController.java
  src/main/java/com/telcreat/aio/viewController/orderController.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/userController.java
  src/main/java/com/telcreat/aio/viewController/variantController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/addProduct.html
  src/main/resources/templates/item.html
  src/main/resources/templates/manageProducts.html
  src/main/resources/templates/shop.html
Labels: bug, enhancement

#35 item.html updated
  src/main/resources/templates/item.html
Labels: bug

#36 Added Latitude and Longitude variables to Shop Edit View
  src/main/java/com/telcreat/aio/model/ShopEditForm.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/static/img/item/init.txt.txt
  src/main/resources/static/img/shop/init.txt.txt
  src/main/resources/static/img/shopBackground/init.txt.txt
  src/main/resources/static/img/user/init.txt.txt
  src/main/resources/static/img/variant/init.txt.txt
  src/main/resources/templates/editShop.html
Labels: bug, enhancement

#37 Added functionality to change Item Category
  src/main/java/com/telcreat/aio/model/ItemEditForm.java
  src/main/java/com/telcreat/aio/repo/ItemRepo.java
  src/main/java/com/telcreat/aio/service/ItemService.java
  src/main/java/com/telcreat/aio/viewController/itemController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/addProduct.html
  src/main/resources/templates/h_products.html
  src/main/resources/templates/item.html
  src/main/resources/templates/search.html
Labels: bug, enhancement

#38 Added initial default shop coordinates
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/search.html
Labels: bug, enhancement

#40 Searching functionality and some error correction.
  src/main/java/com/telcreat/aio/repo/ItemRepo.java
  src/main/java/com/telcreat/aio/service/ItemService.java
  src/main/java/com/telcreat/aio/service/ShopService.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/search.html
Labels: bug, enhancement

#41 Added User Orders view
  src/main/java/com/telcreat/aio/repo/ShopOrderRepo.java
  src/main/java/com/telcreat/aio/service/SendEmail.java
  src/main/java/com/telcreat/aio/service/ShopOrderService.java
  src/main/java/com/telcreat/aio/viewController/orderController.java
  src/main/java/com/telcreat/aio/viewController/userController.java
  src/main/resources/templates/h_orders.html
  src/main/resources/templates/userOrders.html
Labels: bug, enhancement

#42 fragments correction
  src/main/resources/templates/fragments.html
Labels: bug

#43 Improvements in searching system.
  src/main/java/com/telcreat/aio/service/ShopService.java
  src/main/java/com/telcreat/aio/viewController/viewController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/search.html
Labels: bug, enhancement

#44 Important changes in Email Service handling
  src/main/java/com/telcreat/aio/service/EmailSenderThread.java
  src/main/java/com/telcreat/aio/service/SendEmail.java
  src/main/java/com/telcreat/aio/service/ShopOrderService.java
  src/main/java/com/telcreat/aio/service/UserService.java
  src/main/java/com/telcreat/aio/viewController/userController.java
Labels: enhancement

#45 IMPORTANT CHANGE IN SHOP COORDINATES
  pom.xml
  src/main/java/com/telcreat/aio/AioApplication.java
  src/main/java/com/telcreat/aio/model/ShopEditForm.java
  src/main/java/com/telcreat/aio/model/Variant.java
  src/main/java/com/telcreat/aio/service/CartService.java
  src/main/java/com/telcreat/aio/service/OpenStreetMapUtils.java
  src/main/java/com/telcreat/aio/viewController/cartController.java
  src/main/java/com/telcreat/aio/viewController/shopController.java
  src/main/java/com/telcreat/aio/viewController/userController.java
  src/main/resources/templates/addProduct.html
  src/main/resources/templates/cart.html
  src/main/resources/templates/editShop.html
  src/main/resources/templates/h_cesta.html
  src/main/resources/templates/userOrders.html
Labels: enhancement
